name: Build and deploy ASP.Net Core app to Azure Web App - periscope

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 1. BUILD LE FRONTEND (VUE.JS)
      - name: Install and Build Vue App
        run: |
          cd src/Web/vue-app
          npm install
          npm run build
        # Note : Assure-toi que ton vite.config.ts exporte vers ../wwwroot

      # 2. PUBLISH UNIQUEMENT LE PROJET WEB (PAS LES TESTS)
      - name: dotnet publish
        run: dotnet publish src/Web/Web.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish # On télécharge dans un dossier propre

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4517DC9DB2E84447A497149E62135F41 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EBF90701A23547B1A39ECD9B21CEF8E1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_67AC9F4E3A624704A177AF3A4DFAC314 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'periscope'
          slot-name: 'Production'
          package: ./publish # On pointe sur le dossier téléchargé
